import Head from "next/head";
import Footer from "../components/commons/Footer";
import Navbar from "../components/commons/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Some COntent
    </div>
  );
}
